import "@fortawesome/fontawesome-svg-core/styles.css";

import { Config } from "@fortawesome/fontawesome-svg-core";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/navbar";
import Link from "next/link";
import Footer from "@/components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar></Navbar>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
